language: java

sudo: false

dist: trusty

jdk:
  - oraclejdk7
  - oraclejdk8
  - oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

env:
  - GRADLE_OPTS="--add-opens java.base/java.lang=ALL-UNNAMED --permit-illegal-access"

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
after_success:
  - bash <(curl -s https://codecov.io/bash)